apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
  labels:
    app: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier-container
          image: cassiozareck/little-ecom-notifier:latest
          ports:
            - containerPort: 8080
