apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      name: auth
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: cassiozareck/little-ecom-auth
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: db-config
          ports:
              - containerPort: 8080
      restartPolicy: Always
