
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "auth-volume"
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/auth
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi

