apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  - JWT_KEY: secure-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: db-config
data:
  DB_USER: "auth-admin"
  DB_PASSWORD: "123123"
  DATABASE_URL: "postgresql://auth-admin:123123@auth:5432/my_database"
