apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_KEY: c2VjdXJlLXNlY3JldA==

---
apiVersion: v1
kind: Secret
metadata:
  name: db-config
data:
  DB_USER: YXV0aA==
  DB_PASSWORD: MTIzMTIz
  DB_HOST: MTkyLjE2OC4zLjkK
