apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Auth
  template:
    metadata:
      name: Auth
      labels:
        app: Auth
    spec:
      containers:
        - name: auth
          image: Image
          imagePullPolicy: Always
        - name: postgres
          image: postgres

      restartPolicy: Always
